/**
 * Engine Thermal Overheat & Radiator Cooling System.
 *
 * Models engine block temperature (°C), load-dependent heat generation,
 * airflow dissipation, and rapid thermal cooling when fording cold rivers.
 */

export interface EngineThermalState {
  temperatureCelsius: number; // Normal: 85°C, Overheat threshold: 110°C
  isOverheated: boolean;
  powerMultiplier: number; // Derates engine power if overheated (1.0 -> 0.6)
  warningIndicator: boolean;
}

export function updateEngineThermalState(
  currentState: EngineThermalState,
  engineLoad: number, // 0..1
  speedMps: number,
  isFordingWater: boolean,
  ambientTempCelsius: number,
  deltaSeconds: number,
): EngineThermalState {
  // Heat generated by heavy pulling engine load
  const heatGen = engineLoad * 4.2 * deltaSeconds;
  // Radiator airflow & water cooling
  const waterCoolingBonus = isFordingWater ? 4.0 : 1.0;
  const coolingRate = (0.015 + speedMps * 0.005) * waterCoolingBonus;
  const heatDissipate = (currentState.temperatureCelsius - ambientTempCelsius) * coolingRate * deltaSeconds;


  const newTemp = Math.max(
    ambientTempCelsius,
    Math.min(130, currentState.temperatureCelsius + heatGen - heatDissipate),
  );

  const isOverheated = newTemp >= 110;
  const warningIndicator = newTemp >= 102;
  const powerMultiplier = newTemp >= 115 ? 0.6 : newTemp >= 110 ? 0.8 : 1.0;

  return {
    temperatureCelsius: Number(newTemp.toFixed(1)),
    isOverheated,
    powerMultiplier,
    warningIndicator,
  };
}
